name: Hello World Action
on: workflow_dispatch


jobs:
  # Job name
  say-hello:
    runs-on: ubuntu-latest # Github hosted runners
    steps:
      - name: Greet the world
        uses: daws-88s/workflows/.github/actions/hello-world@main
        with:
          who-to-greet: 'Sivakumar'
